apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  labels:
    app.kubernetes.io/instance: opa-gatekeeper
  name: k8srequiredsecurity
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredProbes
      validation:
        openAPIV3Schema:
          properties:
            probes:
              type: array
              items:
                type: string
            probeTypes:
              type: array
              items:
                type: string
            exemptContainers:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredprobes
        violation[{"msg": msg}] {
          securityContext := input.review.object.spec.securityContext
          exempt := {ignore | ignore := input.parameters.exemptContainers[_]}
          not exempt[container.name] 
          probe := input.parameters.probes[_]
          not container[probe]
          msg := sprintf("Container <%v> in your <%v> <%v> has no <%v>", [container.name, input.review.kind.kind, input.review.object.metadata.name, probe])
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          exempt := {ignore | ignore := input.parameters.exemptContainers[_]}
          not exempt[container.name]
          probe := input.parameters.probes[_]
          container[probe]
          not check_probe_type(container, probe)
          probe_types := {type | type := input.parameters.probeTypes[_]}
          msg := sprintf("Probe <%v> in container <%v> in  <%v> <%v> has none of the required probetypes <%v>", [probe,container.name, input.review.kind.kind, input.review.object.metadata.name, probe_types])
        }


        check_probe_type(container, probe) = true {
           probe_types := {type | type := input.parameters.probeTypes[_]}
           container[probe][key]
           probe_types[key]
        }
