apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default

  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      namespace: istio-system

  addonComponents:
    tracing:
      enabled: true
    kiali:
      enabled: true

  # Global Helm settings
  values:
    global:
      controlPlaneSecurityEnabled: true
      mtls:
        enabled: true

      # https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt

    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true

    gateways:
      istio-ingressgateway:
        autoscaleMin: 3
        cpu:
          targetAverageUtilization: 60