---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-collector
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
data:
  opa.conf: |
{{- if .Values.collect.objects }}
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "status.gatekeeper.sh/v1beta1"
      insecure_ssl false
      <watch>
        resource_name constraint_template_pod_statuses
      </watch>
      <watch>
        resource_name constraint_pod_statuses
      </watch>
    </source>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "templates.gatekeeper.sh/v1alpha1"
      insecure_ssl false
      <watch>
        resource_name constraint_templates
      </watch>
    </source>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "config.gatekeeper.sh/v1alpha1"
      insecure_ssl false
      <watch>
        resource_name configs
      </watch>
    </source>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "constraints.gatekeeper.sh/v1alpha1"
      insecure_ssl false
      <watch>
        resource_name k8s_allowed_repos
      </watch>
      <watch>
        resource_name k8s_banned_image_tags
      </watch>
      <watch>
        resource_name k8s_block_node_port
      </watch>
      <watch>
        resource_name k8s_container_limits
      </watch>
      <watch>
        resource_name k8s_container_ratios
      </watch>
      <watch>
        resource_name k8s_external_ips
      </watch>
      <watch>
        resource_name k8s_https_only
      </watch>
      <watch>
        resource_name k8s_image_digests
      </watch>
      <watch>
        resource_name k8s_no_annotation_values
      </watch>
      <watch>
        resource_name k8s_protected_namespaces
      </watch>
      <watch>
        resource_name k8s_pspallow_privilege_escalation_container
      </watch>
      <watch>
        resource_name k8s_pspallowed_users
      </watch>
      <watch>
        resource_name k8s_pspapp_armor
      </watch>
      <watch>
        resource_name k8s_pspcapabilities
      </watch>
      <watch>
        resource_name k8s_pspflex_volumes
      </watch>
      <watch>
        resource_name k8s_pspforbidden_sysctls
      </watch>
      <watch>
        resource_name k8s_psphost_filesystem
      </watch>
      <watch>
        resource_name k8s_psphost_namespace
      </watch>
      <watch>
        resource_name k8s_psphost_networking_ports
      </watch>
      <watch>
        resource_name k8s_pspprivileged_container
      </watch>
      <watch>
        resource_name k8s_pspproc_mount
      </watch>
      <watch>
        resource_name k8s_pspread_only_root_filesystem
      </watch>
      <watch>
        resource_name k8s_pspseccomp
      </watch>
      <watch>
        resource_name k8s_pspselinux_v2
      </watch>
      <watch>
        resource_name k8s_deny_sadefault
      </watch>
      <watch>
        resource_name k8s_pspvolume_types
      </watch>
      <watch>
        resource_name k8s_pvc_limits
      </watch>
      <watch>
        resource_name k8s_regulated_resources
      </watch>
      <watch>
        resource_name k8s_required_label_values
      </watch>
      <watch>
        resource_name k8s_required_labels
      </watch>
      <watch>
        resource_name k8s_required_probes
      </watch>
      <watch>
        resource_name k8s_unique_ingress_host
      </watch>
      <watch>
        resource_name k8s_unique_service_selector
      </watch>
      <watch>
        resource_name restricted_taint_toleration
      </watch>
    </source>
{{- end }}
    <source>
      @type kubernetes_objects
      <storage>
        path /fluentd/var/checkpoint/opa-objects
      </storage>

      tag opa.violations.*
      api_version "constraints.gatekeeper.sh/v1alpha1"
      insecure_ssl false
{{- if .Values.collect.violations.allowedDockerRegistries }}
      <watch>
        resource_name k8s_allowed_repos
      </watch>
{{- end }}
{{- if .Values.collect.violations.bannedImageTags }}
      <watch>
        resource_name k8s_banned_image_tags
      </watch>
{{- end }}
{{- if .Values.collect.violations.blockNodePort }}
      <watch>
        resource_name k8s_block_node_port
      </watch>
{{- end }}
{{- if .Values.collect.violations.noBigContainers }}
      <watch>
        resource_name k8s_container_limits
      </watch>
{{- end }}
{{- if .Values.collect.violations.containerRatio }}
      <watch>
        resource_name k8s_container_ratios
      </watch>
{{- end }}
{{- if .Values.collect.violations.allowedIPs }}
      <watch>
        resource_name k8s_external_ips
      </watch>
{{- end }}
{{- if .Values.collect.violations.httpsOnly }}
      <watch>
        resource_name k8s_https_only
      </watch>
{{- end }}
{{- if .Values.collect.violations.imageDigest }}
      <watch>
        resource_name k8s_image_digests
      </watch>
{{- end }}
{{- if .Values.collect.violations.podsHaveIstio }}
      <watch>
        resource_name k8s_no_annotation_values
      </watch>
{{- end }}
      # <watch>
      #   resource_name k8s_protected_namespaces
      # </watch>
{{- if .Values.collect.violations.noPrivilegedEscalation }}
      <watch>
        resource_name k8s_pspallow_privilege_escalation_container
      </watch>
{{- end }}
{{- if .Values.collect.violations.allowedUsers }}
      <watch>
        resource_name k8s_pspallowed_users
      </watch>
{{- end }}
{{- if .Values.collect.violations.allowedAppArmorProfiles }}
      <watch>
        resource_name k8s_pspapp_armor
      </watch>
{{- end }}
{{- if .Values.collect.violations.allowedCapabilities }}
      <watch>
        resource_name k8s_pspcapabilities
      </watch>
{{- end }}

{{- if .Values.collect.violations.allowedFlexVolumes }}
      <watch>
        resource_name k8s_pspflex_volumes
      </watch>
{{- end }}
{{- if .Values.collect.violations.noDefaultServiceAccount }}
      <watch>
        resource_name k8s_deny_sadefault
      </watch>
{{- end }}
{{- if .Values.collect.violations.noSysctls }}
      <watch>
        resource_name k8s_pspforbidden_sysctls
      </watch>
{{- end }}
{{- if .Values.collect.violations.allowedHostFilesystem }}
      <watch>
        resource_name k8s_psphost_filesystem
      </watch>
{{- end }}
{{- if .Values.collect.violations.noHostNamespace }}
      <watch>
        resource_name k8s_psphost_namespace
      </watch>
{{- end }}
{{- if .Values.collect.violations.hostNetworking }}
      <watch>
        resource_name k8s_psphost_networking_ports
      </watch>
{{- end }}
{{- if .Values.collect.violations.noPrivilegedContainers }}
      <watch>
        resource_name k8s_pspprivileged_container
      </watch>
{{- end }}
{{- if .Values.collect.violations.allowedProcMount }}
      <watch>
        resource_name k8s_pspproc_mount
      </watch>
{{- end }}
{{- if .Values.collect.violations.readOnlyRoot }}
      <watch>
        resource_name k8s_pspread_only_root_filesystem
      </watch>
{{- end }}
{{- if .Values.collect.violations.allowedSecCompProfiles }}
      <watch>
        resource_name k8s_pspseccomp
      </watch>
{{- end }}
{{- if .Values.collect.violations.selinuxPolicy }}
      <watch>
        resource_name k8s_pspselinux_v2
      </watch>
{{- end }}
{{- if .Values.collect.violations.volumeTypes }}
      <watch>
        resource_name k8s_pspvolume_types
      </watch>
{{- end }}
      # <watch>
      #   resource_name k8s_pvc_limits
      # </watch>
      # <watch>
      #   resource_name k8s_regulated_resources
      # </watch>
{{- if .Values.collect.violations.namespacesHaveIstio }}
      <watch>
        resource_name k8s_required_label_values
      </watch>
{{- end }}
{{- if .Values.collect.violations.requiredLabels }}
      <watch>
        resource_name k8s_required_labels
      </watch>
{{- end }}
{{- if .Values.collect.violations.requiredProbes }}
      <watch>
        resource_name k8s_required_probes
      </watch>
{{- end }}
{{- if .Values.collect.violations.uniqueIngressHost }}
      <watch>
        resource_name k8s_unique_ingress_host
      </watch>
{{- end }}
{{- if .Values.collect.violations.uniqueServiceSelector }}
      <watch>
        resource_name k8s_unique_service_selector
      </watch>
{{- end }}
{{- if .Values.collect.violations.restrictedTaint }}
      <watch>
        resource_name restricted_taint_toleration
      </watch>
{{- end }}
    </source>
  pods.conf: |
{{- if .Values.collect.objects }}
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "v1"
      insecure_ssl false
      <watch>
        resource_name pods
      </watch>
      <watch>
        resource_name namespaces
      </watch>
      <watch>
        resource_name events
      </watch>
    </source>
{{- end }}
  outputs.conf: |
{{- if .Values.collect.objects }}
    <match kube.**>
      @type elasticsearch
      include_tag_key true
      port 9200
      scheme https
      ca_file /etc/elasticsearch/certs/ca.crt
      host {{ .Values.elasticsearch.name }}-es-http
      user elastic
      password "#{ENV['ELASTIC_PASSWORD']}"
      reload_connections false
      reload_after 100
      loglevel debug
      logstash_format true
      logstash_prefix objects
    </match>
{{- end }}
    <match violations.**>
      @type elasticsearch
      @log_level debug
      suppress_type_name true
      include_tag_key true
      id_key _hash
      remove_keys _hash
      port 9200
      scheme https
      ca_file /etc/elasticsearch/certs/ca.crt
      host {{ .Values.elasticsearch.name }}-es-http
      user elastic
      password "#{ENV['ELASTIC_PASSWORD']}"
      reload_connections false
      reload_after 100
      logstash_format true
      logstash_prefix violations
      <buffer>
        flush_interval 30s
        flush_at_shutdown true
      </buffer>
    </match>
    <match>
      @type stdout
    </match>
  filters.conf: |
{{- if .Values.collect.objects }}
    <filter kube.objects.pods>
      @type jq_transformer
      # in ruby '\\' will escape and become just '\', since we need two '\' in the `gsub` jq filter, it becomes '\\\\'.
      jq '.record.source = "namespace:\(env.MY_NAMESPACE)/pod:\(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\\\."; ":")) | .record'
    </filter>
    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.state = [ .record.object.status.containerStatuses | .[0]? | select(has("state")) |  .state | keys[]  ]| .record '
    </filter>
    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.reason = [ .record.object.status.containerStatuses | .[0]?.state | .. | .reason?  | select (. !=null) ] | .record '
    </filter>
    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.images = [ .record.object.status.containerStatuses | .[]?.image ] | .record'
    </filter>
    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.imageIDs = [.record.object.status.containerStatuses | .[]?.imageID ] | .record '
    </filter>

    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.phase = [.record.object.status.phase ] | .record '
    </filter>

    # variable status fields cause input errors. So we extracted the values we want above 
    # and then clear out the rest of the status here:
    <filter kube.objects.*>
      @type record_transformer
      remove_keys $.object.metadata.managedFields
    </filter>
    # This replaces all . with _ in labels/annotations/etc.  This causes issues when there are multiple labels in the environment:
    # app: foo and app.kubernetes.io/something: foo since app is both a field and an object, so Elasticsearch cannot
    # understand how to parse
    <filter kube.**>
      @type dedot
      de_dot_nested true
      de_dot_separator _
    </filter>
{{- end }}
    <match opa.violations.**>
      @type exec_filter
      command jq -c --unbuffered 'select( .object.status.totalViolations != 0 ) | .auditTimestamp=.object.status.auditTimestamp | .object.status.violations[]+={"auditTimestamp":.auditTimestamp} | .object.status.violations[]'
      <format>
        @type json
      </format>
      <parse>
        @type json
        # force a small buffer, as the json parser doesn't flush until it's full.  0 doesn't work, 8 causes missed events, 
        # and 1 seems to force all event immediately.
        stream_buffer_size 1
        time_type string
        time_key auditTimestamp
      </parse>
      tag violations
    </match>
    <filter violations.**>
      @type elasticsearch_genid
      hash_id_key _hash
      include_time_in_seed true
      use_record_as_seed true
      record_keys enforcementAction,kind,message,name
    </filter>
  fluent.conf: |
    <system>
      log_level {{ .Values.loglevel }}
    </system>
    @include pods.conf
    @include opa.conf
    @include filters.conf
    @include outputs.conf
