---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-collector
  labels:
    app.kubernetes.io/component: collection
data:
  opa.conf: |
{{- if .Values.collect.objects }}
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "status.gatekeeper.sh/v1beta1"
      insecure_ssl false
      <watch>
        resource_name constraint_template_pod_statuses
      </watch>
      <watch>
        resource_name constraint_pod_statuses
      </watch>
    </source>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "templates.gatekeeper.sh/v1alpha1"
      insecure_ssl false
      <watch>
        resource_name constraint_templates
      </watch>
    </source>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "config.gatekeeper.sh/v1alpha1"
      insecure_ssl false
      <watch>
        resource_name configs
      </watch>
    </source>
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "constraints.gatekeeper.sh/v1alpha1"
      insecure_ssl false
      <watch>
        resource_name k8s_required_labels
      </watch>
      <watch>
        resource_name k8s_required_label_values
      </watch>
      <watch>
        resource_name k8s_no_annotation_values
      </watch>
      <watch>
        resource_name k8s_required_probes
      </watch>
      <watch>
        resource_name k8s_allowed_repos
      </watch>
      <watch>
        resource_name k8s_container_limits
      </watch>
      <watch>
        resource_name k8s_pvc_limits
      </watch>
      <watch>
        resource_name k8s_protected_namespaces
      </watch>
      <watch>
        resource_name k8s_regulated_resources
      </watch>
      <watch>
        resource_name k8s_banned_image_tags
      </watch>
      <watch>
        resource_name k8s_psp_allowed_privilege_escalation_container
      </watch>
    </source>
{{- end }}
    <source>
      @type kubernetes_objects
      <storage>
        path /fluentd/var/checkpoint/opa-objects
      </storage>

      tag opa.violations.*
      api_version "constraints.gatekeeper.sh/v1alpha1"
      insecure_ssl false
      {{ if .Values.violations.noPriviligedContainers }}
      <watch>
        resource_name k8s_psp_allowed_privilege_escalation_container
      </watch>
      {{- end }}
      </watch>
{{- if .Values.collect.violations.labels}}
      <watch>
        resource_name k8s_required_labels
      </watch>
      <watch>
        resource_name k8s_required_label_values
      </watch>
{{- end}}
      # <watch>
      #   resource_name k8s_no_annotation_values
      # </watch>
      # <watch>
      #   resource_name k8s_required_probes
      # </watch>
{{- if .Values.collect.violations.repositories }}
      <watch>
        resource_name k8s_allowed_repos
      </watch>
{{- end }}
      # <watch>
      #   resource_name k8s_container_limits
      # </watch>
      # <watch>
      #   resource_name k8s_pvc_limits
      # </watch>
      # <watch>
      #   resource_name k8s_protected_namespaces
      # </watch>
      # <watch>
      #   resource_name k8s_regulated_resources
      # </watch>
      # <watch>
      #   resource_name k8s_banned_image_tags
      # </watch>
    </source>
  pods.conf: |
{{- if .Values.collect.objects }}
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      api_version "v1"
      insecure_ssl false
      <watch>
        resource_name pods
      </watch>
      <watch>
        resource_name namespaces
      </watch>
      <watch>
        resource_name events
      </watch>
    </source>
{{- end }}
  outputs.conf: |
{{- if .Values.collect.objects }}
    <match kube.**>
      @type elasticsearch
      include_tag_key true
      port 9200
      scheme https
      ca_file /etc/elasticsearch/certs/ca.crt
      host {{ .Values.elasticsearch.name }}-es-http
      user elastic
      password "#{ENV['ELASTIC_PASSWORD']}"
      reload_connections false
      reload_after 100
      loglevel debug
      logstash_format true
      logstash_prefix objects
    </match>
{{- end }}
    <match violations.**>
      @type elasticsearch
      include_tag_key true
      port 9200
      scheme https
      ca_file /etc/elasticsearch/certs/ca.crt
      host {{ .Values.elasticsearch.name }}-es-http
      user elastic
      password "#{ENV['ELASTIC_PASSWORD']}"
      reload_connections false
      reload_after 100
      loglevel trace
      logstash_format true
      logstash_prefix violations
      replace_dots true
      <buffer>
        flush_mode immediate
        flush_thread_count 8
      </buffer>
    </match>
    <match>
      @type stdout
    </match>
  filters.conf: |
{{- if .Values.collect.objects }}
    <filter kube.objects.pods>
      @type jq_transformer
      # in ruby '\\' will escape and become just '\', since we need two '\' in the `gsub` jq filter, it becomes '\\\\'.
      jq '.record.source = "namespace:\(env.MY_NAMESPACE)/pod:\(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\\\."; ":")) | .record'
    </filter>
    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.state = [ .record.object.status.containerStatuses | .[0]? | select(has("state")) |  .state | keys[]  ]| .record '
    </filter>
    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.reason = [ .record.object.status.containerStatuses | .[0]?.state | .. | .reason?  | select (. !=null) ] | .record '
    </filter>
    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.images = [ .record.object.status.containerStatuses | .[]?.image ] | .record'
    </filter>
    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.imageIDs = [.record.object.status.containerStatuses | .[]?.imageID ] | .record '
    </filter>

    <filter kube.objects.pods>
      @type jq_transformer
      jq '.record.phase = [.record.object.status.phase ] | .record '
    </filter>

    # variable status fields cause input errors. So we extracted the values we want above 
    # and then clear out the rest of the status here:
    <filter kube.objects.*>
      @type record_transformer
      remove_keys $.object.metadata.managedFields
    </filter>
    # This replaces all . with _ in labels/annotations/etc.  This causes issues when there are multiple labels in the environment:
    # app: foo and app.kubernetes.io/something: foo since app is both a field and an object, so Elasticsearch cannot
    # understand how to parse
    <filter kube.**>
      @type dedot
      de_dot_nested true
      de_dot_separator _
    </filter>
{{- end }}
    <match opa.violations.*>
      @type jq
      jq 'select( .record.object.status.totalViolations != 0 ) |  .record.object.status.violations'
      # jq '{source: .record.object.metadata.labels["cluster-auditor.dso.mil/source"], control: .record.object.metadata.labels["cluster-auditor.dso.mil/control"], violations: .record.object.status.violations} | { source: .source, control: .control, violation: .violations[]} | {source: .source, control: .control, kind: .violation.kind, message: .violation.message, name: .violation.name, namespace: .violation.namespace}'
      # tag violations.*
      label @VIOLATIONS
      remove_tag_prefix opa
    </match>

  fluent.conf: |
    <system>
      log_level {{ .Values.loglevel }}
    </system>
    @include pods.conf
    @include opa.conf
    @include filters.conf
    @include outputs.conf
