apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
  name: opa-exporter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-exporter
  strategy: {}
  template:
    metadata:
      labels:
        app: opa-exporter
        {{- include "clusterauditor.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      {{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        name: opa-exporter
        resources:
{{ toYaml .Values.resources | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      serviceAccountName: opa-exporter
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

