apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-collector
  labels:
    app.kubernetes.io/component: fluentd
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      engine: fluentd
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
      labels:
        engine: fluentd
    spec:
      serviceAccountName: cluster-audit-logging
      terminationGracePeriodSeconds: 30
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: opa-collector
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        env:
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.elasticsearch.name }}-es-elastic-user
                key: elastic
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: conf-configmap
          mountPath: /fluentd/etc
        - name: elasticsearch-certs
          mountPath: /etc/elasticsearch/certs/
        - name: checkpoint
          mountPath: /fluentd/var/checkpoint
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: checkpoint
        emptyDir: {}
      - name: conf-configmap
        configMap:
          name: opa-collector
      - name: elasticsearch-certs
        secret:
          secretName: {{ .Values.elasticsearch.name }}-es-http-certs-public
