apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opa-exporter
  name: opa-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-exporter
  strategy: {}
  template:
    metadata:
      labels:
        app: opa-exporter
    spec:
      containers:
      - image: registry.dso.mil/platform-one/big-bang/apps/core/cluster-auditor/opa-exporter:v0.0.3
        name: opa-scorecard-exporter-ldscm
        resources: {}
