{{ if .Values.elasticsearch.dedicated }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  version: 7.9.2
  image: registry1.dsop.io/ironbank/elastic/elasticsearch/elasticsearch:7.9.2
  nodeSets:
  - name: master
    count: 1
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.store.allow_mmap: true
      index.store.type: mmapfs
      node.ml: false
      xpack.ml.enabled: false
      xpack.security.authc.token.enabled: true
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          fluentbit.io/exclude-istio-proxy: "true"
      spec:
        automountServiceAccountToken: true
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
          resources:
            requests:
              memory: 2Gi
              cpu: 0.5
            limits:
              memory: 3Gi
              cpu: 2
  - name: data
    count: 1
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.store.allow_mmap: true
      index.store.type: mmapfs
      node.ml: false
      xpack.ml.enabled: false
      xpack.security.authc.token.enabled: true
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          fluentbit.io/exclude-istio-proxy: "true"
      spec:
        automountServiceAccountToken: true
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
          resources:
            requests:
              memory: 2Gi
              cpu: 0.5
            limits:
              memory: 3Gi
              cpu: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
---
{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  host: "{{ .Values.elasticsearch.name }}-es-http.{{ .Release.Namespace}}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{ end }}
{{ end }}