{{ if .Values.elasticsearch.dedicated }} 
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.9.2
  image: registry1.dsop.io/ironbank/elastic/kibana/kibana:7.9.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      automountServiceAccountToken: true
  http:
    tls:
      selfSignedCertificate: {}
---
{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cluster-audit-kabana
spec:
  hosts:
    - cluster-auditor.bigbang.dev
  gateways:
  - main.istio-system.svc.cluster.local
  http:
    - route:
        - destination:
            host: kibana-kb-http
            port:
              number: 5601
{{ end }}
{{ end }}