{{- if and .Values.istio.enabled .Values.monitoring.enabled (eq .Values.istio.mtls.mode "STRICT") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: cluster-auditor-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app: opa-exporter
  portLevelMtls:
    "9141":
      mode: PERMISSIVE
{{- end }}
