{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opa-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: opa-exporter
{{- end }}