apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opa-exporter
  namespace: logging
  labels:
    release: opa-exporter
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: cluster-auditor
