apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opa-exporter
  namespace: monitoring
  labels:
    release: monitoring-monitoring
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: opa-exporter
