apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBannedImageTags
metadata:
  name: ban-latest-tag
  labels:
    cluster-auditor.dsop.io/source: kubernetes-stig
    cluster-auditor.dsop.io/control: "90"
spec:
  enforcementAction: dryrun  
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    tags:
      - "latest"