---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/clusterRole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-audit-starboard
rules:
  - apiGroups: [""]
    resources:
    - pods
    - events
    - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - "aquasecurity.github.io"
    resources:
    - "*"
    verbs: ["get", "list", "watch"]
