{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns-egress-allow-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: UDP
    {{- if .Values.openshift }}
    - port: 5353
      protocol: UDP
    {{- end }}
  podSelector: {}
  policyTypes:
  - Egress
{{- end }}
