{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
  name: es-communication
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "clusterauditor.labels" . | nindent 10 }}
    ports:
    - port: 9200
      protocol: TCP
  podSelector:
    matchLabels:
      common.k8s.elastic.co/type: elasticsearch
  policyTypes:
  - Ingress
{{- end }}
