apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: all-egress-cluster-auditor
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
        # ONLY Block requests to AWS metadata IP
        except:
        - 169.254.169.254/32
  podSelector:
    matchLabels:
      {{- include "clusterauditor.labels" . | nindent 6 }}
  policyTypes:
  - Egress
