bases:
- ../base/internal

namespace: elastic

patchesJson6902:
  - target:
      group: elasticsearch.k8s.elastic.co
      version: v1
      kind: Elasticsearch
      name: elasticsearch
    path: patches/patch.elasticsearch.yaml
  - target:
      group: kibana.k8s.elastic.co
      version: v1
      kind: Kibana
      name: kibana
    path: patches/patch.kibana.yaml
