collect:
  objects: false
  violations:
    repositories: true

violations:
  allowedDockerRegistries:
  - "registry1.dsop.io"
image:
  repo: docker.io/runyonsolutions/cluster-auditor
  tag: 0.3
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 600Mi