apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
resources:
  - k8s-apps-labels.yaml
  - no-ignore-istio.yaml
  - ns-has-istio-label.yaml
  - probes-must-be-provided.yaml
  - repo1.yaml
  - no-latest-tag.yaml
