{{- if .Values.violations.allowedUsers.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: psp-pods-allowed-user-ranges
spec:
  enforcementAction: {{ .Values.violations.allowedUsers.enforcementAction }}
  match:
    {{- if .Values.violations.allowedUsers.match  }}
    {{- toYaml .Values.violations.allowedUsers.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.allowedUsers.parameters | nindent 4}}
{{- end }}