{{- if .Values.violations.allowedHostFilesystem.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostFilesystem
metadata:
  name: psp-host-filesystem
  labels:
    constraints.cluster-auditor/name: "Host Filesystem Paths"
    constraints.cluster-auditor/description: "Containers may not use volumes mapped to the host node, unless the path is specified."
    constraints.cluster-auditor/scope: "Pod"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy/host-filesystem"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/concepts/storage/volumes/#hostpath"
spec:
  enforcementAction: {{ .Values.violations.allowedHostFilesystem.enforcementAction }}
  match:
    {{- if .Values.violations.allowedHostFilesystem.match  }}
    {{- toYaml .Values.violations.allowedHostFilesystem.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.allowedHostFilesystem.parameters | nindent 4}}
{{- end }}