{{- if .Values.violations.allowedUsers.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: psp-pods-allowed-user-ranges
spec:
  enforcementAction: {{ .Values.violations.allowedUsers.enforcementAction }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
    - kube-system
  parameters:
    {{- toYaml .Values.violations.allowedUsers.parameters | nindent 4}}
{{- end }}