{{- if .Values.violations.allowedFlexVolumes.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPFlexVolumes
metadata:
  name: psp-flexvolume-drivers
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
  annotations:
    constraints.cluster-auditor/name: "Flex Volume Drivers"
    constraints.cluster-auditor/description: "Containers may only use Flex Volumes with the specified drivers"
    constraints.cluster-auditor/scope: "Pod"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy/flexvolume-drivers"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/concepts/storage/volumes/#flexvolume"
    constraints.cluster-auditor/related: "https://github.com/kubernetes/community/blob/master/contributors/devel/sig-storage/flexvolume.md"
spec:
  enforcementAction: {{ .Values.violations.allowedFlexVolumes.enforcementAction }}
  match:
    {{- if .Values.violations.allowedFlexVolumes.match  }}
    {{- toYaml .Values.violations.allowedFlexVolumes.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.allowedFlexVolumes.parameters | nindent 4}}
{{- end }}