{{- if .Values.violations.allowedProcMount.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPProcMount
metadata:
  name: psp-proc-mount
spec:
  enforcementAction: {{ .Values.violations.allowedProcMount.enforcementAction }}
  match:
    {{- if .Values.violations.allowedProcMount.match  }}
    {{- toYaml .Values.violations.allowedProcMount.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.allowedProcMount.parameters | nindent 4}}
{{- end }}