{{- if .Values.violations.allowedProcMount.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPProcMount
metadata:
  name: psp-proc-mount
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
    constraints.cluster-auditor/name: "Proc Mount"
    constraints.cluster-auditor/description: "Containers may only use the specified ProcMount types."
    constraints.cluster-auditor/scope: "Pod"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy/proc-mount"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1"
spec:
  enforcementAction: {{ .Values.violations.allowedProcMount.enforcementAction }}
  match:
    {{- if .Values.violations.allowedProcMount.match  }}
    {{- toYaml .Values.violations.allowedProcMount.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.allowedProcMount.parameters | nindent 4}}
{{- end }}