{{- if .Values.violations.bannedImageTags.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBannedImageTags
metadata:
  name: ban-image-tags
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
    constraints.cluster-auditor/name: "Banned Image Tags"
    constraints.cluster-auditor/description: "Container Images cannot use specified tags"
    constraints.cluster-auditor/scope: "Pod"
    constraints.cluster-auditor/source: "Unspecified"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/concepts/containers/images/#image-names"
spec:
  enforcementAction: {{ .Values.violations.bannedImageTags.enforcementAction }}
  match:
    {{- if .Values.violations.bannedImageTags.match  }}
    {{- toYaml .Values.violations.bannedImageTags.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.bannedImageTags.parameters | nindent 4}}
{{- end }}