{{- if .Values.violations.bannedImageTags.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBannedImageTags
metadata:
  name: ban-image-tags
spec:
  enforcementAction: {{ .Values.violations.bannedImageTags.enforcementAction }}
  match:
    {{- if .Values.violations.bannedImageTags.match  }}
    {{- toYaml .Values.violations.bannedImageTags.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.bannedImageTags.parameters | nindent 4}}
{{- end }}