apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimits
metadata:
  name: no-big-containers
  labels:
    cluster-auditor.dso.mil/source: big-bang
    cluster-auditor.dso.mil/control: "tbd"
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpu: 2000m
    memory: 4G
    exemptContainers: [""]
