{{- if .Values.violations.hostNetworking.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostNetworkingPorts
metadata:
  name: psp-host-network-ports
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
  annotations:
    constraints.cluster-auditor/name: "Host Network Ports"
    constraints.cluster-auditor/description: "Container images may only use host ports that are specified."
    constraints.cluster-auditor/scope: "Pod"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy/host-network-ports"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#hosts-namespaces"
    constraints.cluster-auditor/related: "https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces"
spec:
  enforcementAction: {{ .Values.violations.hostNetworking.enforcementAction  }}
  match:
    {{- if .Values.violations.hostNetworking.match  }}
    {{- toYaml .Values.violations.hostNetworking.match | nindent 4 }}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.hostNetworking.parameters | nindent 4}}
{{- end }}