{{- if .Values.violations.httpsOnly.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHttpsOnly
metadata:
  name: ingress-https-only
  labels:
    constraints.cluster-auditor/name: "Ingress on HTTPS Only"
    constraints.cluster-auditor/description: "Ingress must only allow HTTPS connections."
    constraints.cluster-auditor/scope: "Ingress"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/httpsonly"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#ingressspec-v1beta1-extensions"
    constraints.cluster-auditor/related: "https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#disabling_http"
spec:
  enforcementAction: {{ .Values.violations.httpsOnly.enforcementAction }}
  match:
    {{- if .Values.violations.httpsOnly.match  }}
    {{- toYaml .Values.violations.httpsOnly.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
{{- end }}