{{- if .Values.violations.blockNodePort.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockNodePort
metadata:
  name: block-node-port
  labels:
    constraints.cluster-auditor/name: "Node Ports"
    constraints.cluster-auditor/description: "Services must not use node ports."
    constraints.cluster-auditor/scope: "Service"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/block-nodeport-services"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/concepts/services-networking/service/#nodeport"
spec:
  enforcementAction: {{ .Values.violations.blockNodePort.enforcementAction  }}
  match:
    {{- if .Values.violations.blockNodePort.match  }}
    {{- toYaml .Values.violations.blockNodePort.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
{{- end }}