{{- if .Values.violations.noPrivilegedContainers.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata:
  name: psp-privileged-container
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
  annotations:
    constraints.cluster-auditor/name: "Privilged Containers"
    constraints.cluster-auditor/description: "Containers must not run as privileged."
    constraints.cluster-auditor/scope: "Pod"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy/privileged-containers"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/concepts/workloads/pods/#privileged-mode-for-containers"
spec:
  enforcementAction: {{ .Values.violations.noPrivilegedContainers.enforcementAction  }}
  match:
    {{- if .Values.violations.noPrivilegedContainers.match  }}
    {{- toYaml .Values.violations.noPrivilegedContainers.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
{{- end }}