{{- if .Values.violations.noSysctls.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPForbiddenSysctls
metadata:
  name: psp-forbidden-sysctls
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
    constraints.cluster-auditor/name: "SysCtls"
    constraints.cluster-auditor/description: "Containers must not use specified sysctls."
    constraints.cluster-auditor/scope: "Pod"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy/forbidden-sysctls"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#setting-sysctls-for-a-pod"
    constraints.cluster-auditor/related: "https://man7.org/linux/man-pages/man8/sysctl.8.html"
spec:
  enforcementAction: {{ .Values.violations.noSysctls.enforcementAction }}
  match:
    {{- if .Values.violations.noSysctls.match  }}
    {{- toYaml .Values.violations.noSysctls.match | nindent 4 }}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.noSysctls.parameters | nindent 4}}
{{- end }}