{{- if or .Values.collect.violations.labels .Values.violations.namespacesHaveIstio.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabelValues
metadata:
  name: ns-must-have-istio
spec:
  enforcementAction: {{ .Values.violations.namespacesHaveIstio.enforcementAction }}
  match:
    {{- if .Values.violations.namespacesHaveIstio.match  }}
    {{- toYaml .Values.violations.namespacesHaveIstio.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    {{- toYaml .Values.violations.namespacesHaveIstio.parameters | nindent 4}}
{{- end }}