{{- if .Values.violations.requiredProbes.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredProbes
metadata:
  name: must-have-probes
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
  annotations:
    constraints.cluster-auditor/name: "Probes"
    constraints.cluster-auditor/description: "Container must have specified probes and probe types."
    constraints.cluster-auditor/scope: "Pod"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/requiredprobes"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/"
    constraints.cluster-auditor/related: "https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes"
spec:
  enforcementAction: {{ .Values.violations.requiredProbes.enforcementAction }}
  match:
    {{- if .Values.violations.requiredProbes.match  }}
    {{- toYaml .Values.violations.requiredProbes.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.requiredProbes.parameters | nindent 4}}
{{- end }}