{{- if .Values.violations.requiredProbes.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredProbes
metadata:
  name: must-have-probes
  labels:
    app.kubernetes.io/instance: opa-gatekeeper
    cluster-auditor.dso.mil/source: kubernetes-stig
    cluster-auditor.dso.mil/control: "00"
spec:
  enforcementAction: {{ .Values.violations.requiredProbes.enforcementAction }}
  match:
    {{- if .Values.violations.requiredProbes.match  }}
    {{- toYaml .Values.violations.requiredProbes.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.requiredProbes.parameters | nindent 4}}
{{- end }}