---
{{- if .Values.violations.readOnlyRoot.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPReadOnlyRootFilesystem
metadata:
  name: read-only-rootsystem
  labels:
    cluster-auditor.dso.mil/source: big-bang
    cluster-auditor.dso.mil/control: "tbd"
spec:
  enforcementAction: {{ .Values.violations.readOnlyRoot.enforcementAction  }}
  match:
    {{- if .Values.violations.readOnlyRoot.match  }}
    {{- toYaml .Values.violations.readOnlyRoot.match | nindent 4 }}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
{{- end }}