{{- if .Values.violations.restrictedTaint.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictedTaintToleration
metadata:
  name: privileged
spec:
  enforcementAction: {{ .Values.violations.restrictedTaint.enforcementAction }}
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    {{- if .Values.violations.restrictedTaint.match  }}
    {{- toYaml .Values.violations.restrictedTaint.match | nindent 4}}
    {{- end }}
  parameters:
    {{- toYaml .Values.violations.restrictedTaint.parameters | nindent 4}}
{{- end }}
