{{- if .Values.violations.restrictedTaint.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictedTaintToleration
metadata:
  name: privileged
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
  annotations:
    constraints.cluster-auditor/name: "Taints and Tolerations"
    constraints.cluster-auditor/description: "Container must be configured according to specified taint and toleration rules."
    constraints.cluster-auditor/scope: "Pod"
    constraints.cluster-auditor/source: "https://github.com/stackrox/blog-examples/tree/master/code/opa-gatekeeper-taint-tolerations"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/"
    constraints.cluster-auditor/related: "https://www.openshift.com/blog/better-kubernetes-security-with-open-policy-agent-opa-part-2"
spec:
  enforcementAction: {{ .Values.violations.restrictedTaint.enforcementAction }}
  match:
    {{- if .Values.violations.restrictedTaint.match  }}
    {{- toYaml .Values.violations.restrictedTaint.match | nindent 4}}
    {{- end }}
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.restrictedTaint.parameters | nindent 4}}
{{- end }}