{{- if .Values.violations.uniqueIngressHost.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sUniqueIngressHost
metadata:
  name: unique-ingress-host
  labels:
    constraints.cluster-auditor/name: "Unique Ingress Hosts"
    constraints.cluster-auditor/description: "Ingress hosts must be unique."
    constraints.cluster-auditor/scope: "Ingress"
    constraints.cluster-auditor/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/uniqueingresshost"
    constraints.cluster-auditor/docs: "https://kubernetes.io/docs/concepts/services-networking/ingress/"
spec:
  enforcementAction: {{ .Values.violations.uniqueIngressHost.enforcementAction  }}
  match:
    {{- if .Values.violations.uniqueIngressHost.match  }}
    {{- toYaml .Values.violations.uniqueIngressHost.match | nindent 4 }}
    {{- end }}
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
{{- end }}