---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/clusterRole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-audit-logging
rules:
  - apiGroups: [""]
    resources:
    - pods
    - events
    verbs: ["get", "list", "watch"]
