apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  labels:
    app.kubernetes.io/component: storage
  name: elasticsearch
  namespace: elastic
spec:
  nodeSets:
  - config:
      index.store.type: mmapfs
      node.data: true
      node.ingest: true
      node.master: true
      node.ml: false
      node.store.allow_mmap: true
      xpack.ml.enabled: false
    count: 1
    name: default
    podTemplate:
      metadata:
        annotations:
          fluentbit.io/exclude-istio-proxy: "true"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
      spec:
        automountServiceAccountToken: true
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          name: elasticsearch
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
            requests:
              cpu: 500m
              memory: 3Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
      status: {}
  transport:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
  updateStrategy:
    changeBudget: {}
  version: 7.6.1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: elasticsearch
spec:
  host: "elasticsearch-es-http.cluster-audit.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

